module.exports = {
  apps: [
    {
      name: "crm",
      script: "./dist/index.js",
      instances: 2,
      exec_mode: "cluster",
      env: {
        NODE_ENV: process.env.NODE_ENV,
        PORT: process.env.PORT,
        DATABASE_URL: process.env.DATABASE_URL,
        EVOLUTION_SERVER_URL: process.env.EVOLUTION_SERVER_URL,
        REDIS_DATABASE_URL: process.env.REDIS_DATABASE_URL,
        REDIS_OFC_PORT: process.env.REDIS_OFC_PORT,
        REDIS_OFC_PASSWORD: process.env.REDIS_OFC_PASSWORD,
        CHATBOT_WEBHOOK: process.env.CHATBOT_WEBHOOK,
        CHATBOT_AUTH_TOKEN: process.env.CHATBOT_AUTH_TOKEN,
        DB_VIABILIDADE_HOST: process.env.DB_VIABILIDADE_HOST,
        DB_VIABILIDADE_PORT: process.env.DB_VIABILIDADE_PORT,
        DB_VIABILIDADE_NAME: process.env.DB_VIABILIDADE_NAME,
        DB_VIABILIDADE_USER: process.env.DB_VIABILIDADE_USER,
        DB_VIABILIDADE_PASSWORD: process.env.DB_VIABILIDADE_PASSWORD,
        GOOGLE_GEOCODE_API_KEY: process.env.GOOGLE_GEOCODE_API_KEY,
        GOOGLE_GEOCODE_API_URL: process.env.GOOGLE_GEOCODE_API_URL,
        FRONT_URL: process.env.FRONT_URL,
        IMAGEM_URL: process.env.IMAGEM_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        ADM: process.env.ADM,
        BKO_VENDA: process.env.BKO_VENDA,
        BKO_TRATATIVA: process.env.BKO_TRATATIVA,
        CONSULTOR: process.env.CONSULTOR,
        FB_ACCESS_TOKEN: process.env.FB_ACCESS_TOKEN,
        FB_BASE_URL: process.env.FB_BASE_URL,
        REDIS_URL: process.env.REDIS_URL,
      },
      watch: false,
      max_memory_restart: "1G",
    },
  ],
};
